#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# Kill applications if they are running already
pkill picom
pkill sxhkd
pkill polybar
# pkill dunst

# AutoStart applications
xsetroot -cursor_name left_ptr &
xrandr --output HDMI-0 --scale '1.7x1.7' &
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
wired &
polybar &
# dunst &
blueman-applet &
nm-applet $
xsetroot -cursor_name left_ptr &

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
