#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X
# two monitors DP
# my monitor in lima
# if xrandr | grep "HDMI-0 connected"; then
#     bspc monitor DP-1 -d I II III IV V VI VII
#     bspc monitor HDMI-0 -d VIII IX X
# my monitor in usa (PAST LAYOUT)
# if xrandr | grep "HDMI-0 connected"; then
#     bspc monitor DP-1 -d IV V VI VII VIII IX X
#     bspc monitor HDMI-0 -d I II III
# else
#     bspc monitor DP-1 -d I II III IV V VI VII VIII IX X
# fi

# Config monitor new layout
if xrandr | grep "HDMI-0 connected"; then
    bspc monitor DP-1 -d I II III
    bspc monitor HDMI-0 -d IV V VI VII VIII IX X
else
    bspc monitor DP-1 -d I II III IV V VI VII VIII IX X
fi

# bspc config border_width 2
# bspc config window_gap 12
bspc config border_width 6
bspc config window_gap 10

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config normal_border_color "#110b0d"

# Kill applications if they are running already
pkill picom
pkill polybar
# pkill clipcatd
pkill pasystray
pkill slimbookbattery
# pkill dunst

# Power manager
xfce4-power-manager &
# AutoStart applications
nitrogen --restore &
flameshot &
xsetroot -cursor_name left_ptr &
xrandr --output HDMI-0 --scale '1.6x1.6' &
picom --config $HOME/.config/picom/picom.conf &
slimbookbattery --minimize &
wired &
# polybar &
if xrandr | grep "HDMI-0 connected"; then
    polybar --reload --config=$HOME/.config/polybar/monitor/config.ini &
else
    polybar --reload &
fi
pasystray &
clipcatd &
# change battery profile
~/.config/bspwm/battery-profile.sh &
# dunst &
blueman-applet &
nm-applet $
# slimbookbattery &
xsetroot -cursor_name left_ptr &

# asuscommands:
# asusctl bios -D 0 # MUX switch to: 0 = Discrete GPU, 1 = Optimus
# asusctl profile -l # list profiles
# asusctl profile -n # toggle between profiles
# asusctl profile -P Performance # set profile to performance
# asusctl profile -P Balanced # set profile to balanced
# asusctl profile -P Quiet # set profile to quiet
# asusctl profile -p # show current profiles

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
#
# remember that i am using auto-cpu-freq to manage cpu frequency
# so i don't need to set the governor here
# make zoom always floating
bspc rule -a zoom desktop='^8' state=floating

# TODO: find a way to make this work
# Open steam games in X workspace
steamlib="$HOME/.local/share/Steam"
mygames=$(ls $steamlib/steamapps/appmanifest_*.acf | sed 's/[^0-9]*//g') # this sed command removes everything but the digits

for game in $mygames; do
    bspc rule -a steam_app_$game desktop=^10 state=fullscreen
done
