#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X
# two monitors DP
if xrandr | grep "HDMI-0 connected"; then
    bspc monitor DP-1 -d I II III IV V VI VII
    bspc monitor HDMI-0 -d VIII IX X
else
    bspc monitor HDMI-0 -d I II III IV V VI VII
fi

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# Kill applications if they are running already
pkill picom
pkill polybar
# pkill dunst

# AutoStart applications
nitrogen --restore &
flameshot &
xsetroot -cursor_name left_ptr &
xrandr --output HDMI-0 --scale '1.7x1.7' &
picom --config $HOME/.config/picom/picom.conf &
wired &
polybar &
clipcatd &
# dunst &
blueman-applet &
nm-applet $
# slimbookbattery &
xsetroot -cursor_name left_ptr &

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
#
# remember that i am using auto-cpu-freq to manage cpu frequency
# so i don't need to set the governor here
